# Generated by Django 3.1.7 on 2021-04-07 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanse19', '0002_auto_20210407_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowd_counting',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='face_mask',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ip_address',
            name='user_id',
        ),
        migrations.AddField(
            model_name='crowd_counting',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='face_mask',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ip_address',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
