# Generated by Django 3.1.7 on 2021-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanse19', '0003_auto_20210407_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_mask', models.BooleanField(default=False)),
                ('crowd_counting', models.BooleanField(default=False)),
                ('social_distancing', models.BooleanField(default=False)),
            ],
        ),
    ]
