# Generated by Django 3.1.7 on 2021-04-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanse19', '0004_recording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
