# Generated by Django 3.1.7 on 2021-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanse19', '0008_social_distancing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_address',
            name='crowd_ip',
        ),
        migrations.RemoveField(
            model_name='ip_address',
            name='face_mask_ip',
        ),
        migrations.AddField(
            model_name='ip_address',
            name='ip_address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ip_address',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
