# Generated by Django 3.1.7 on 2021-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanse19', '0011_crowd_counting_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowd_counting',
            name='last_mail_time',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-05 08:38:58.138774'),
            preserve_default=False,
        ),
    ]
