# Generated by Django 3.1.7 on 2021-05-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanse19', '0012_crowd_counting_last_mail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='face_mask',
            name='last_mail_time',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-05 08:38:58.138774'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social_distancing',
            name='last_mail_time',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-05 08:38:58.138774'),
            preserve_default=False,
        ),
    ]
