face_weights = '/home/sparsh/COVID-19/face/yolov3_training_last.weights'
face_cfg = '/home/sparsh/COVID-19/face/yolov3_testing.cfg'
crowd_prototxt = '/home/sparsh/COVID-19/people counting/mobilenet_ssd/MobileNetSSD_deploy.prototxt'
crowd_caffemodel = '/home/sparsh/COVID-19/people counting/mobilenet_ssd/MobileNetSSD_deploy.caffemodel'
social_cfg = '/home/sparsh/COVID-19/social distancing/social-distancing-detector-master/yolo-coco/yolov3.cfg'
social_weights = '/home/sparsh/COVID-19/social distancing/social-distancing-detector-master/yolo-coco/yolov3.weights' 